GET http://127.0.0.1:5001/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4Mzc4Nzk1Zi04NTU4LTQ0MmQtYjhlZC1hN2U4YWY3NzM2NDYiLCJpYXQiOjE3ODc3NjM5ODIsImV4cCI6MTc4Nzc2NzU4Mn0.vZkm-Tvl6RfEhlantDmdhPGVqASLzxfOLENAJX-h80c